name: Create web release

on:
    workflow_dispatch:
        inputs:
            widget-name:
                description: "Web Widget/Module to release"
                required: true

jobs:
    release:
        name: "Create web widget/module release"
        runs-on: ubuntu-latest

        steps:
            - name: "Checking-out code"
              uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2
              with:
                  submodules: false
            - name: "Defining node version"
              uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # v2
              with:
                  node-version-file: '.nvmrc'
            - name: "Installing dependencies"
              run: npm run bootstrap
            - name: "Building ${{ github.event.inputs.widget-name }}"
              run: "npm run release -- --scope '${{ github.event.inputs.widget-name }}'"
            - name: "Creating ${{ github.event.inputs.widget-name }} widget release"
              if: ${{ endsWith(github.event.inputs.widget-name, '-web') }}
              run: "npm run release-github:widget '${{ github.event.inputs.widget-name }}'"
              env:
                  GH_USERNAME: ${{ secrets.GH_USERNAME }}
                  GH_EMAIL: ${{ secrets.GH_EMAIL }}
                  GH_NAME: ${{ secrets.GH_NAME }}
                  GH_PAT: ${{ secrets.GH_PAT }}
            - name: "Creating ${{ github.event.inputs.widget-name }} module release"
              if: ${{ !endsWith(github.event.inputs.widget-name, '-web') }}
              run: "npm run create-modules:web '${{ github.event.inputs.widget-name }}'"
              env:
                  GH_USERNAME: ${{ secrets.GH_USERNAME }}
                  GH_EMAIL: ${{ secrets.GH_EMAIL }}
                  GH_NAME: ${{ secrets.GH_NAME }}
                  GH_PAT: ${{ secrets.GH_PAT }}
