name: 'Custom Native Template Dev build'

on:
  workflow_dispatch:
  schedule: 
    - cron: '0 0 * * *'

env:
  EXTRA_DEPENDENCIES: '{"dependencies": {"react-native-inappbrowser-reborn": "3.4.0"}}'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Native Template from release/6.2.0
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 #v2.4.0
        with: 
          repository: 'mendix/native-template'
          ref: 'release/6.2.0'
      - name: Set up JDK 11
        uses: actions/setup-java@f0bb91606209742fe3ea40199be2f3ef195ecabf #v2.5.0
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Setup node
        uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 #v2.5.1
        with:
          node-version: '14.18.3'
      - name: Setup extra dependencies
        uses: smarki/modify-package-dependencies@e53345cf2995abc32203c920bec609606fa94f52 #0.5.0
        with: 
          extra-dependencies: '${{env.EXTRA_DEPENDENCIES}}'
      - name: NPM install
        uses: Jaid/action-npm-install@9483da054882538350947c4147de4c8adbf0d597 #v1.2.4
        with:
          packageManager: npm
      - name: Setup NDK 21.0.6113669
        uses: nttld/setup-ndk@b2abc75192ee2a1ec118c8238fd86dec6d96dc43 #v1.0.6
        with:
          ndk-version: r21e
      - name: Build with Gradle
        run: ./gradlew assembleDevDebug
        working-directory: ./android
      - name: Archive apk
        uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 #v2.3.1
        with:
          name: native-template-6-dev-apk
          path: android/app/build/outputs/apk/dev/debug/app-dev-debug.apk