name: Publish widget data
on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
jobs:
  publish-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: npm install
      - run: npm run data:widgets
      - uses: peter-evans/create-pull-request@v3
        with:
          branch: build/update-widgets-data
          delete-branch: true
          commit-message: 'chore: update widgets data file'
          title: 'chore: Update widgets data file'
          draft: false
          add-paths: 'data/widgets.json'
