name: Publish widget data
on:
    push:
        branches:
            - master
        paths:
            - packages/**/*
            - scripts/data/**/*
    pull_request:
        branches:
            - master
        paths:
            - scripts/data/**/*
jobs:
    publish-data:
        runs-on: ubuntu-latest
        steps:
            - name: "Checking out code"
              uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2
              with:
                  submodules: false
            - name: "Defining node version"
              uses: actions/setup-node@5b52f097d36d4b0b2f94ed6de710023fbb8b2236 # v3
              with:
                  node-version-file: ".nvmrc"
                  cache: "npm"
                  cache-dependency-path: "**/package-lock.json"
            - name: "Installing dependencies"
              run: npm ci
            - name: "Exporting data"
              run: npm run content-overview:data
            - name: Archive production artifacts
              uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2
              with:
                  name: content.json
                  path: data/content.json
            - name: "Set env variable"
              run: echo "BASEPATH=/$GITHUB_REF_NAME" >> $GITHUB_ENV
            - name: "Creating overview"
              run: |
                  npm run content-overview:site:build
                  npm run content-overview:site:export
            - name: "Creating pull request"
              if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
              id: cpr
              uses: peter-evans/create-pull-request@dcd5fd746d53dd8de555c0f10bca6c35628be47a # v3
              with:
                  token: ${{ secrets.GH_PAT }}
                  branch: build/update-widgets-data
                  delete-branch: true
                  commit-message: "chore: update content data file"
                  title: "chore: Update content data file"
                  draft: false
                  add-paths: "data/content.json"
            - name: "Enabling auto-merge for pull-request, if new"
              if: steps.cpr.outputs.pull-request-operation == 'created'
              uses: peter-evans/enable-pull-request-automerge@d2ede5636b3febc92809259995e643565e675aab # v1
              with:
                  token: ${{ secrets.GH_PAT }}
                  pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
                  merge-method: merge
            - name: "Setting AWS credentials"
              if: >-
                  (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name ==
                  github.repository) || (github.event_name == 'push' && github.ref == 'refs/heads/master')
              uses: aws-actions/configure-aws-credentials@05b148adc31e091bafbaf404f745055d4d3bc9d2 # v1.6.1
              with:
                  aws-access-key-id: ${{ secrets.AWS_CONTENT_DATA_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_CONTENT_DATA_SECRET }}
                  aws-region: eu-central-1
            - name: "Copy data to out folder"
              run:
                cp data/content.json scripts/data/out/content.json
            - name: "Uploading to S3"
              if: >-
                  (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name ==
                  github.repository) || (github.event_name == 'push' && github.ref == 'refs/heads/master')
              run: |
                  aws s3 sync scripts/data/out s3://widgetresources-data/$GITHUB_REF_NAME/
                  echo https://widgetresources-data.s3.eu-central-1.amazonaws.com/$GITHUB_REF_NAME/index.html
